# @hostname = http://localhost:4000
@hostname = https://server-aperezl.cloud.okteto.net


GET {{hostname}}/math/4/5
###

GET {{hostname}}/api/articles/2Bj7jf9emeaObcf4
###

GET {{hostname}}/api/users
###

POST {{hostname}}/api/users
Content-Type: application/json

{
  "username": "user2",
  "password": "1234",
  "email": "user2@example.com"
}
###
POST {{hostname}}/api/login
Content-Type: application/json

{
  "email": "user2@example.com",
  "password": "1234"
}